name: Unzip File

on: [push]

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Unzip file
        run: unzip whaticket-main.zip -d destino/

      - name: Commit extracted files
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add .
          git commit -m "Descompactando arquivo automaticamente"
          git push
